spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashopV2
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

# jwt:
#  header: Authorization
#  secret: and0LXRlc3QtYWxqamFiYWVsdaf90asdfasdgy18j34kr87naS1qd3QtdGVzdC1hbGgargr1324asdf1234asdfpqYWJhZWdpLWp3dC10ZXN0LWFsamphYmFlZ2ktand0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdpLWp3dC10ZXN0LWFsamphYmFlZ2ktand0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdp
